# Generated by Django 3.2.5 on 2021-08-01 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='article',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
