# Generated by Django 3.2.5 on 2021-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210805_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
