# Generated by Django 3.2.5 on 2021-08-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_customer_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=500)),
                ('delivery', models.CharField(choices=[('Pickup', 'free'), ('Delivery by mail', 'info'), ('Delivery by courier', 'info')], max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
    ]
