# Generated by Django 3.2.5 on 2021-08-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cartorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
    ]
