# Generated by Django 3.2.5 on 2021-08-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20210821_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='tess',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
