# Generated by Django 3.2.5 on 2021-08-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_cartorder_tess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='test',
        ),
    ]
