# Generated by Django 3.2.5 on 2021-08-22 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_cartorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='article',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
