# Generated by Django 3.2.5 on 2021-08-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_cartorder_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
