# Generated by Django 3.2.5 on 2021-09-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20210905_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
