# Generated by Django 3.2.5 on 2021-09-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_alter_cartorder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
