# Generated by Django 3.2.5 on 2021-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_alter_order_total_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
