# Generated by Django 3.2.5 on 2021-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_cartorder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
    ]
