# Generated by Django 3.2.5 on 2021-10-06 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0032_alter_cartorder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='owner',
            field=models.CharField(default='anonym', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=str, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default=str, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email_or_session',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='cart.customer'),
            preserve_default=False,
        ),
    ]
